version: "3"
services:
  gateway:
    build: ./gateway
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    external_links:
      - nacos-standalone:nacos
  goods-service:
    build: ./goods-service
    container_name: goods-service
    restart: always
    external_links:
      - nacos-standalone:nacos
      - mysql:db
#    depends_on:
#      - nacos
#      - mysql
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    external_links:
      - nacos-standalone:nacos
      - mysql:db
  auth-center:
    build: ./auth-center
    container_name: auth-center
    restart: always
    external_links:
      - nacos-standalone:nacos
      - mysql:db
