version: "3"
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    external_links:
      - nacos-standalone:nacos
      - sentinel-dashboard:sentinel
  auth-center:
    build: ./auth-center
    container_name: auth-center
    external_links:
      - nacos-standalone:nacos
      - mysql:db
      - sentinel-dashboard:sentinel
    ports:
      - "8001:8001"
  goods-service:
    build: ./goods-service
    container_name: goods-service
    external_links:
      - nacos-standalone:nacos
      - mysql:db
      - sentinel-dashboard:sentinel
    ports:
      - "8002:8002"
  user-service:
    build: ./user-service
    container_name: user-service
    external_links:
      - nacos-standalone:nacos
      - mysql:db
      - sentinel-dashboard:sentinel
    ports:
      - "8003:8003"

