spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8711
        dashboard: localhost:8858
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd

#logging:
#  level:
#    com.alibaba.nacos: error
#    org.springframework.cloud.sleuth: debug

logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
    com.micro.mall: debug
    web: debug
  pattern:
    console:
      "%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
      %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
wx:
  miniapp:
    configs:
      - appid: wxe59f8a6e001da64c #微信小程序的appid
        secret: 39875e6a506bee4a9c0ede573dc54423 #微信小程序的Secret
#        token: #微信小程序消息服务器配置的token
#        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
appid: wxe59f8a6e001da64c


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app-name: goods-service
  author: zhb1nk&sux111
  email: zhbink@163.com