spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: auth
server:
  port: 8041
#logging:
#  level:
#    com.alibaba.nacos: error
#    org.springframework.cloud.sleuth: debug

logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
      - appid: wxe59f8a6e001da64c #微信小程序的appid
        secret: 39875e6a506bee4a9c0ede573dc54423 #微信小程序的Secret
#        token: #微信小程序消息服务器配置的token
#        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
appid: wxe59f8a6e001da64c