spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: true
    sentinel:
      transport:
        port: 8710
        dashboard: sentinel:8858
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app-name: goods-service
  author: zhb1nk&sux111
  email: zhbink@163.com