server:
  port: 8002
spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
feign:
  client:
    config:
      default:
        loggerLevel: FULL
        #针对某个级别设置输出级别(设置局部的优先级别是最高的)
      Book-service:
        loggerLevel: FULL
