spring:
  application:
    name: goods
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods_service?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8712
        dashboard: localhost:8858

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app-name: goods-service
  author: zhb1nk&sux111
  email: zhbink@163.com

rocketmq:
  name-server: localhost:9876
  producer:
    group: my-group
