server:
  port: 8001
spring:
#  datasource:
#    url:  jdbc:mysql://49.232.161.14:3306/user_service?useUnicode=true&characterEncoding=utf-8
#    hikari:
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848