#server:
#  port: 8001
#
#spring:
#  application:
#    name: data-show
#  datasource:
#    # 当前数据源操作类型
#    type: com.alibaba.druid.pool.DruidDataSource
#    # mysql驱动包
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456



